git:
  depth: 5
  
stages:
  - "Build and Test"
  - "Package"
  
jobs:
  include:
    - stage: "Build and Test"
      language: java
      jdk: oraclejdk11
      before_script:
        - cd sample-application-backend
      script:
        - echo "Maven build & test"
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=EnzoContinho_sample-application-students
        - echo "Run test coverage and Quality Gate ---- NOT IMPLEMENTED YET"
    - stage: "Build and Test"
      language: node.js
      node_js: "12.20"
      before_script:
        - cd sample-application-frontend
      script:
        - echo "NPM install and build"
        - npm run test
    - stage: "Package"
      before_script:
        - cd sample-application-backend
      script:
        - echo "Docker build ..."
        - docker build -t 22mars1998/sample-application-students_backend .
        - echo "Docker login ..."
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
        - echo "Docker push ..."
        - docker push 22mars1998/sample-application-students_backend
      on:
        branch: develop  
    - stage: "Package"
      before_script:
        - cd sample-application-frontend
      script:
        - echo "Docker build ..."
        - docker build -t 22mars1998/sample-application-students_frontend .
        - echo "Docker login ..."
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
        - echo "Docker push ..."
        - docker push 22mars1998/sample-application-students_frontend
      on:
        branch: develop
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"
services:
- docker
addons:
  sonarcloud:
    organization: "enzocontinho"
    token: "$SONARCLOUD_TOKEN"